/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as DrawsRouteImport } from './routes/draws'
import { Route as EnsembleRouteImport } from './routes/ensemble'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as RussiaRouteImport } from './routes/russia'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as StructureRouteImport } from './routes/structure'
import { Route as ApiPublicHooksUk49sSyncRouteImport } from './routes/api/public/hooks/uk49s-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawsRoute = DrawsRouteImport.update({
  id: '/draws',
  path: '/draws',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsembleRoute = EnsembleRouteImport.update({
  id: '/ensemble',
  path: '/ensemble',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const RussiaRoute = RussiaRouteImport.update({
  id: '/russia',
  path: '/russia',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureRoute = StructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUk49sSyncRoute = ApiPublicHooksUk49sSyncRouteImport.update({
  id: '/api/public/hooks/uk49s-sync',
  path: '/api/public/hooks/uk49s-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/draws': typeof DrawsRoute
  '/ensemble': typeof EnsembleRoute
  '/history': typeof HistoryRoute
  '/predictions': typeof PredictionsRoute
  '/russia': typeof RussiaRoute
  '/strategies': typeof StrategiesRoute
  '/structure': typeof StructureRoute
  '/api/public/hooks/uk49s-sync': typeof ApiPublicHooksUk49sSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/draws': typeof DrawsRoute
  '/ensemble': typeof EnsembleRoute
  '/history': typeof HistoryRoute
  '/predictions': typeof PredictionsRoute
  '/russia': typeof RussiaRoute
  '/strategies': typeof StrategiesRoute
  '/structure': typeof StructureRoute
  '/api/public/hooks/uk49s-sync': typeof ApiPublicHooksUk49sSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/draws': typeof DrawsRoute
  '/ensemble': typeof EnsembleRoute
  '/history': typeof HistoryRoute
  '/predictions': typeof PredictionsRoute
  '/russia': typeof RussiaRoute
  '/strategies': typeof StrategiesRoute
  '/structure': typeof StructureRoute
  '/api/public/hooks/uk49s-sync': typeof ApiPublicHooksUk49sSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/draws'
    | '/ensemble'
    | '/history'
    | '/predictions'
    | '/russia'
    | '/strategies'
    | '/structure'
    | '/api/public/hooks/uk49s-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/draws'
    | '/ensemble'
    | '/history'
    | '/predictions'
    | '/russia'
    | '/strategies'
    | '/structure'
    | '/api/public/hooks/uk49s-sync'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/backtest'
    | '/draws'
    | '/ensemble'
    | '/history'
    | '/predictions'
    | '/russia'
    | '/strategies'
    | '/structure'
    | '/api/public/hooks/uk49s-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  BacktestRoute: typeof BacktestRoute
  DrawsRoute: typeof DrawsRoute
  EnsembleRoute: typeof EnsembleRoute
  HistoryRoute: typeof HistoryRoute
  PredictionsRoute: typeof PredictionsRoute
  RussiaRoute: typeof RussiaRoute
  StrategiesRoute: typeof StrategiesRoute
  StructureRoute: typeof StructureRoute
  ApiPublicHooksUk49sSyncRoute: typeof ApiPublicHooksUk49sSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draws': {
      id: '/draws'
      path: '/draws'
      fullPath: '/draws'
      preLoaderRoute: typeof DrawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensemble': {
      id: '/ensemble'
      path: '/ensemble'
      fullPath: '/ensemble'
      preLoaderRoute: typeof EnsembleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/russia': {
      id: '/russia'
      path: '/russia'
      fullPath: '/russia'
      preLoaderRoute: typeof RussiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure': {
      id: '/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof StructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/uk49s-sync': {
      id: '/api/public/hooks/uk49s-sync'
      path: '/api/public/hooks/uk49s-sync'
      fullPath: '/api/public/hooks/uk49s-sync'
      preLoaderRoute: typeof ApiPublicHooksUk49sSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  BacktestRoute: BacktestRoute,
  DrawsRoute: DrawsRoute,
  EnsembleRoute: EnsembleRoute,
  HistoryRoute: HistoryRoute,
  PredictionsRoute: PredictionsRoute,
  RussiaRoute: RussiaRoute,
  StrategiesRoute: StrategiesRoute,
  StructureRoute: StructureRoute,
  ApiPublicHooksUk49sSyncRoute: ApiPublicHooksUk49sSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
