/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DrawsRouteImport } from './routes/draws'
import { Route as EnsembleRouteImport } from './routes/ensemble'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RussiaRouteImport } from './routes/russia'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as StructureRouteImport } from './routes/structure'
import { Route as ApiPublicHooksManusWebhookRouteImport } from './routes/api/public/hooks/manus-webhook'
import { Route as ApiPublicHooksResearchWeeklyRouteImport } from './routes/api/public/hooks/research-weekly'
import { Route as ApiPublicHooksRussiaSyncRouteImport } from './routes/api/public/hooks/russia-sync'
import { Route as ApiPublicHooksUk49sSyncRouteImport } from './routes/api/public/hooks/uk49s-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawsRoute = DrawsRouteImport.update({
  id: '/draws',
  path: '/draws',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsembleRoute = EnsembleRouteImport.update({
  id: '/ensemble',
  path: '/ensemble',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RussiaRoute = RussiaRouteImport.update({
  id: '/russia',
  path: '/russia',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureRoute = StructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksManusWebhookRoute =
  ApiPublicHooksManusWebhookRouteImport.update({
    id: '/api/public/hooks/manus-webhook',
    path: '/api/public/hooks/manus-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResearchWeeklyRoute =
  ApiPublicHooksResearchWeeklyRouteImport.update({
    id: '/api/public/hooks/research-weekly',
    path: '/api/public/hooks/research-weekly',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRussiaSyncRoute =
  ApiPublicHooksRussiaSyncRouteImport.update({
    id: '/api/public/hooks/russia-sync',
    path: '/api/public/hooks/russia-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksUk49sSyncRoute = ApiPublicHooksUk49sSyncRouteImport.update({
  id: '/api/public/hooks/uk49s-sync',
  path: '/api/public/hooks/uk49s-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/dashboard': typeof DashboardRoute
  '/draws': typeof DrawsRoute
  '/ensemble': typeof EnsembleRoute
  '/history': typeof HistoryRoute
  '/predictions': typeof PredictionsRoute
  '/research': typeof ResearchRoute
  '/russia': typeof RussiaRoute
  '/strategies': typeof StrategiesRoute
  '/structure': typeof StructureRoute
  '/api/public/hooks/manus-webhook': typeof ApiPublicHooksManusWebhookRoute
  '/api/public/hooks/research-weekly': typeof ApiPublicHooksResearchWeeklyRoute
  '/api/public/hooks/russia-sync': typeof ApiPublicHooksRussiaSyncRoute
  '/api/public/hooks/uk49s-sync': typeof ApiPublicHooksUk49sSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/dashboard': typeof DashboardRoute
  '/draws': typeof DrawsRoute
  '/ensemble': typeof EnsembleRoute
  '/history': typeof HistoryRoute
  '/predictions': typeof PredictionsRoute
  '/research': typeof ResearchRoute
  '/russia': typeof RussiaRoute
  '/strategies': typeof StrategiesRoute
  '/structure': typeof StructureRoute
  '/api/public/hooks/manus-webhook': typeof ApiPublicHooksManusWebhookRoute
  '/api/public/hooks/research-weekly': typeof ApiPublicHooksResearchWeeklyRoute
  '/api/public/hooks/russia-sync': typeof ApiPublicHooksRussiaSyncRoute
  '/api/public/hooks/uk49s-sync': typeof ApiPublicHooksUk49sSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/dashboard': typeof DashboardRoute
  '/draws': typeof DrawsRoute
  '/ensemble': typeof EnsembleRoute
  '/history': typeof HistoryRoute
  '/predictions': typeof PredictionsRoute
  '/research': typeof ResearchRoute
  '/russia': typeof RussiaRoute
  '/strategies': typeof StrategiesRoute
  '/structure': typeof StructureRoute
  '/api/public/hooks/manus-webhook': typeof ApiPublicHooksManusWebhookRoute
  '/api/public/hooks/research-weekly': typeof ApiPublicHooksResearchWeeklyRoute
  '/api/public/hooks/russia-sync': typeof ApiPublicHooksRussiaSyncRoute
  '/api/public/hooks/uk49s-sync': typeof ApiPublicHooksUk49sSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/analysis'
    | '/backtest'
    | '/dashboard'
    | '/draws'
    | '/ensemble'
    | '/history'
    | '/predictions'
    | '/research'
    | '/russia'
    | '/strategies'
    | '/structure'
    | '/api/public/hooks/manus-webhook'
    | '/api/public/hooks/research-weekly'
    | '/api/public/hooks/russia-sync'
    | '/api/public/hooks/uk49s-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/analysis'
    | '/backtest'
    | '/dashboard'
    | '/draws'
    | '/ensemble'
    | '/history'
    | '/predictions'
    | '/research'
    | '/russia'
    | '/strategies'
    | '/structure'
    | '/api/public/hooks/manus-webhook'
    | '/api/public/hooks/research-weekly'
    | '/api/public/hooks/russia-sync'
    | '/api/public/hooks/uk49s-sync'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/analysis'
    | '/backtest'
    | '/dashboard'
    | '/draws'
    | '/ensemble'
    | '/history'
    | '/predictions'
    | '/research'
    | '/russia'
    | '/strategies'
    | '/structure'
    | '/api/public/hooks/manus-webhook'
    | '/api/public/hooks/research-weekly'
    | '/api/public/hooks/russia-sync'
    | '/api/public/hooks/uk49s-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AnalysisRoute: typeof AnalysisRoute
  BacktestRoute: typeof BacktestRoute
  DashboardRoute: typeof DashboardRoute
  DrawsRoute: typeof DrawsRoute
  EnsembleRoute: typeof EnsembleRoute
  HistoryRoute: typeof HistoryRoute
  PredictionsRoute: typeof PredictionsRoute
  ResearchRoute: typeof ResearchRoute
  RussiaRoute: typeof RussiaRoute
  StrategiesRoute: typeof StrategiesRoute
  StructureRoute: typeof StructureRoute
  ApiPublicHooksManusWebhookRoute: typeof ApiPublicHooksManusWebhookRoute
  ApiPublicHooksResearchWeeklyRoute: typeof ApiPublicHooksResearchWeeklyRoute
  ApiPublicHooksRussiaSyncRoute: typeof ApiPublicHooksRussiaSyncRoute
  ApiPublicHooksUk49sSyncRoute: typeof ApiPublicHooksUk49sSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draws': {
      id: '/draws'
      path: '/draws'
      fullPath: '/draws'
      preLoaderRoute: typeof DrawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensemble': {
      id: '/ensemble'
      path: '/ensemble'
      fullPath: '/ensemble'
      preLoaderRoute: typeof EnsembleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/russia': {
      id: '/russia'
      path: '/russia'
      fullPath: '/russia'
      preLoaderRoute: typeof RussiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure': {
      id: '/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof StructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/manus-webhook': {
      id: '/api/public/hooks/manus-webhook'
      path: '/api/public/hooks/manus-webhook'
      fullPath: '/api/public/hooks/manus-webhook'
      preLoaderRoute: typeof ApiPublicHooksManusWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/research-weekly': {
      id: '/api/public/hooks/research-weekly'
      path: '/api/public/hooks/research-weekly'
      fullPath: '/api/public/hooks/research-weekly'
      preLoaderRoute: typeof ApiPublicHooksResearchWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/russia-sync': {
      id: '/api/public/hooks/russia-sync'
      path: '/api/public/hooks/russia-sync'
      fullPath: '/api/public/hooks/russia-sync'
      preLoaderRoute: typeof ApiPublicHooksRussiaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/uk49s-sync': {
      id: '/api/public/hooks/uk49s-sync'
      path: '/api/public/hooks/uk49s-sync'
      fullPath: '/api/public/hooks/uk49s-sync'
      preLoaderRoute: typeof ApiPublicHooksUk49sSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AnalysisRoute: AnalysisRoute,
  BacktestRoute: BacktestRoute,
  DashboardRoute: DashboardRoute,
  DrawsRoute: DrawsRoute,
  EnsembleRoute: EnsembleRoute,
  HistoryRoute: HistoryRoute,
  PredictionsRoute: PredictionsRoute,
  ResearchRoute: ResearchRoute,
  RussiaRoute: RussiaRoute,
  StrategiesRoute: StrategiesRoute,
  StructureRoute: StructureRoute,
  ApiPublicHooksManusWebhookRoute: ApiPublicHooksManusWebhookRoute,
  ApiPublicHooksResearchWeeklyRoute: ApiPublicHooksResearchWeeklyRoute,
  ApiPublicHooksRussiaSyncRoute: ApiPublicHooksRussiaSyncRoute,
  ApiPublicHooksUk49sSyncRoute: ApiPublicHooksUk49sSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
